### ISSUE TITLE
Universe v0.2 Alpha Demo Product Review (Sprint 5)

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#26]
### Issues from Universe v0.2 Alpha Demo Product Review (Sprint 5):

**Original Review**
[Universe v0.2 Alpha Demo Product Review (Sprint 5)](https://github.com/universelabs/universe-marketing/issues/6)

#### Issue List
- [ ] [1. Visual heirarchy content adjustment for signup & signin](https://github.com/universelabs/universe-webapp/issues/24)
- [ ] [2. Add full process email authentication & verification](https://github.com/universelabs/universe-webapp/issues/25)
- [ ] [3. Review and choose colors that express safety](https://github.com/universelabs/universe-webapp/issues/27)
- [ ] [4. Review and simplify app to make more intuitive](https://github.com/universelabs/universe-webapp/issues/28)
- [ ] [5. Look at adding a menu or sidebar to improve dashboard UX](https://github.com/universelabs/universe-webapp/issues/29)
- [ ] [6. Feature Request: Add automatic logout functionality](https://github.com/universelabs/universe-webapp/issues/30)
- [ ] [7. Update html title for dashboard](https://github.com/universelabs/universe-webapp/issues/31)
- [ ] [8. Ensure all key sets are closed and not open](https://github.com/universelabs/universe-webapp/issues/32)
