### ISSUE TITLE
Call : Modestos + Guy

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#5]
**Description**
Call : Modestos + Guy

**Minutes**
- @modkaffes said that @dantrevino's API is working perfectly.
- @modkaffes could use the DigitalOcean credentials.
- Guy to create list of tasks and post in Sprint Kanban Board.
- Talked about storing user's email address and password in mongodb.
- We will send demo users to https://universe.engineering/sign-up where they can sign up.
- There is no link from anywhere to the alpha "sign up" or "log in" page. Users will have the URL or not. We want this to remain somewhat hidden for now.

**Deliverables**
- [x] Guy to invite team to Digital Ocean Team account.
- [x] @dantrevino transfer ownership of droplet to team. https://github.com/universelabs/universe-auth/issues/6 

**Alpha Release Tasks**
- [ ] @modkaffes [#6 Wire up app](https://github.com/universelabs/universe-webapp/issues/6).
- [x] @guylepage3 [#7 Build log in page](https://github.com/universelabs/universe-webapp/issues/7). Use sign up as a reference.
- [ ] @modkaffes [#8 Setup redirect and/or routing](https://github.com/universelabs/universe-webapp/issues/8).
- [ ] @modkaffes [#9 Add copy to clipboard feature](https://github.com/universelabs/universe-webapp/issues/9)
- [ ] @guylepage3 & @pftchal [#10 Alpha pre-release UX review](https://github.com/universelabs/universe-webapp/issues/10).
