### ISSUE TITLE
Move Universe Web App from Heroku to DigitalOcean

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#63]
**Description**
Move Universe Web App from Heroku to DigitalOcean.

>From Modestos
>Modestos Kaffes [10:37 AM]
>With a quick look, I don’t see how the apps being hosted on Heroku will pose an issue to DKIM. From the google support articles posted above, this is something that needs to be changed in DNS Simple

Heroku requires a static IP in order to configure a root domain. We, at Universe, must configure our DNS to root as we cannot have our apps resolving to `www.universe.engineering`. Our DNS must resolve to `universe.engineering` as our TLD is so long and confusing for folks. we’ve received a lot of feedback on this issue.

The catch is that Heroku requires a static IP configuration and Heroku is the only hosting provider out there that does not work with `A records` for root domains.

Heroku’s solution is to use dnsimple.com for aliasing. they have worked with them to provide this service.

So technically, we need to get off DNSimple.com but since we need to resolve to a root domain, we now need to move off of Heroku.

**Tasks**
- [x] Determine whether we should move to ~~Netlify~~ or ~~GCP~~ or ✅DigitalOcean.
- [ ] Setup app on DigitalOcean.
- [ ] Test deployments on new provider.
- [ ] Delete app from Heroku.

**References**
- [Add a custom root domain: Heroku](https://devcenter.heroku.com/articles/custom-domains#add-a-custom-root-domain)

**Comment by guylepage3** [comment]
Pushing this to Sprint 9.

**Comment by guylepage3** [comment]
While migrating over we should also [Setup up dynamic routing with nginx](https://github.com/universelabs/universe-webapp/issues/67)
