### ISSUE TITLE
Move Universe Auth API from Digital Ocean to GCP

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#66]
**Description**
Move Universe Auth API from Digital Ocean to GCP.

**Tasks**
- [x] Determine whether we should move to ~~Netlify~~ or ✅GCP.
- [ ] Setup app on GCP.
- [ ] Test deployments on new provider.
- [ ] Delete app from Heroku.

**Comment by guylepage3** [comment]
Moved to https://github.com/universelabs/universe-auth/issues/13
