### ISSUE TITLE
Refactor & move web client (key management app) to DigitalOcean

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-webapp#67]
**Description**
Refactor & move web client (key management app) from Heroku to DigitalOcean. 

Heroku requires a static IP in order to configure a root domain. We, at Universe, must configure our DNS to root as we cannot have our apps resolving to `www.universe.engineering`. Our DNS must resolve to `universe.engineering` as our TLD is so long and confusing for folks. we’ve received a lot of feedback on this issue.

The catch is that Heroku requires a static IP configuration and Heroku is the only hosting provider out there that does not work with `A records` for root domains.

Heroku’s solution is to use dnsimple.com for aliasing. they have worked with them to provide this service.

So technically, we need to get off DNSimple.com but since we need to resolve to a root domain, we now need to move off of Heroku.

**Tasks**
- [x] Determine whether we should move to ~~Netlify~~ or ~~GCP~~ or ✅DigitalOcean.
- [x] ~~[#56 Understand how to run node.js apps on VM's](https://github.com/universelabs/universe/issues/56)~~
- [ ] Setup app on DigitalOcean.
- [ ] Test deployments on new provider.
- [ ] Delete app from Heroku.

**References**
- [Add a custom root domain: Heroku](https://devcenter.heroku.com/articles/custom-domains#add-a-custom-root-domain)
- [Full Node.js Deployment - NGINX, SSL With Lets Encrypt](https://youtu.be/oykl1Ih9pMg)
- [dynamic routing](https://www.youtube.com/watch?v=5O4TjbbxTxw)
- [ ] [#77 Setup new express server for migration](https://github.com/universelabs/universe.engineering/issues/77)
- [ ] [#78 Setup new website client](https://github.com/universelabs/universe.engineering/issues/78)
